
baseURL = "http://example.org/"
languageCode = "en-us"
title = "pgAssistant Blog"
theme = "PaperMod"
pagination.pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  author = "pgAssistant"
  ShowToc = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"
  disableThemeToggle = false
  env = "production" # nécessaire pour générer l’index
  enableSearch = true

[[menu.main]]
  name = "Posts"
  url = "/post/"
  weight = 1

[[menu.main]]
  name = "Documentation"
  url = "/doc/"
  weight = 1
