
baseURL = "https://beh74.github.io/pgassistant-blog/"
languageCode = "en-us"
title = "pgAssistant Blog"
theme = "PaperMod"
pagination.pagerSize = 10
defaultContentLanguage = "en"

#relativeURLs = true
#canonifyURLs = true

[outputs]
  home = ["HTML", "RSS", "JSON", "SITEMAP"]

[params]
  env = "production"
  title = "pgAssistant Blog"
  description = "Blog about using pgAssistant and PostgreSQL with privacy in mind"
  keywords = ["PostgreSQL", "LLM", "pgAssistant", "Privacy", "Ollama", "Self-hosting"]
  author = "beh74"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowToc = true
  enableSearch = true
  defaultTheme = "auto"
  disableThemeToggle = false
  googleAnalytics = ""


  editPost:
    URL: "https://github.com/beh74/pgassistant-blog/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

[[menu.main]]
  name = "Posts"
  url = "/post/"
  weight = 1

[[menu.main]]
  name = "Documentation"
  url = "/doc/"
  weight = 1


